packages:
  - "apps/*"
  - "packages/*"

catalog:
  # UI Components and Icons
  lucide-react: ^0.468.0  # Latest version tested with Next.js 15.1

  # Core Development Tools
  eslint: ^8.57.0
  prettier: ^3.2.5
  typescript: ^5.3.3

  # TypeScript ESLint
  "@typescript-eslint/parser": ^7.1.0
  "@typescript-eslint/eslint-plugin": ^7.1.0

  # Type Definitions
  "@types/node": ^22.10.2
  "@types/eslint": ^8.56.2

  # Next.js Core
  next: 15.1.0
  "@next/eslint-plugin-next": ^15.1.0
  eslint-config-next: ^15.1.0

  # ESLint Plugins and Configs
  eslint-config-prettier: ^9.1.0
  eslint-plugin-react: ^7.33.2
  eslint-plugin-react-hooks: ^4.6.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-turbo: ^2.3.0
  globals: ^15.1.0

  # Build and Development Tools
  postcss: ^8.4.35
  autoprefixer: ^10.4.17

catalogs:
  react18:
    # React Core
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19
    "@types/react-dom": ^19

  testing:
    # Testing Libraries
    jest: ^29.7.0
    "postcss": ^8
    "tailwindcss": "^3.4.1"
    "eslint": ^9
    "@eslint/eslintrc": ^3